In [1]:
import pandas as pd

cafe = pd.DataFrame({
    '메뉴':   ['아메리카노', '카페라떼', '녹차라떼', '자몽에이드', '레몬에이드'],
    '가격':   [4000, 4500, 5000, 5500, 5000],
    '분류':   ['커피', '커피', '논커피', '음료', '음료'],
    '재고':   [30, 12, 8, 20, 15]
})
cafe

      메뉴    가격   분류  재고
0  아메리카노  4000   커피  30
1   카페라떼  4500   커피  12
2   녹차라떼  5000  논커피   8
3  자몽에이드  5500   음료  20
4  레몬에이드  5000   음료  15

In [ ]:
문제 1. Series vs DataFrame
메뉴 열을 두 가지 방법으로 뽑고, 각각의 타입을 출력하라.

(1) Series로 뽑기
(2) DataFrame(표 모양 유지)으로 뽑기
(3) type()으로 두 결과의 타입이 다름을 확인
💡 힌트: 대괄호 개수 차이

In [24]:
# menu_series = cafe['메뉴','가격','분류','재고']
# menu_series
menu_df = cafe[['메뉴','가격','분류','재고']]
menu_df

      메뉴    가격   분류  재고
0  아메리카노  4000   커피  30
1   카페라떼  4500   커피  12
2   녹차라떼  5000  논커피   8
3  자몽에이드  5500   음료  20
4  레몬에이드  5000   음료  15

In [ ]:
문제 2. loc vs iloc
(1) loc을 사용해 인덱스 1~3 행의 메뉴, 가격 열을 출력하라.
(2) iloc을 사용해 앞 3행, 앞 2열을 출력하라.
(3) 두 결과에서 몇 개의 행이 나왔는지 비교하고, 왜 다른지 한 줄로 설명하라.
💡 힌트: loc은 끝 포함, iloc은 끝 제외

In [53]:
# (1)
cafe.loc[1:3,['메뉴','가격']]

      메뉴    가격
1   카페라떼  4500
2   녹차라떼  5000
3  자몽에이드  5500

In [46]:
# (2)
cafe.iloc[0:3, 0:2]

      메뉴    가격
0  아메리카노  4000
1   카페라떼  4500
2   녹차라떼  5000